from typing import Any, Dict, List, Literal, Optional, Union
from uuid import UUID, uuid4
from pydantic import BaseModel, Field

# --- A2A Infrastructure ---

class A2AMessage(BaseModel):
    """Standardized envelope for SOTA Agent-to-Agent communication."""
    message_id: UUID = Field(default_factory=uuid4)
    correlation_id: UUID = Field(..., description="Tracing ID for the entire conversation flow")
    from_agent: str
    to_agent: str
    intent: str
    payload: Dict[str, Any]
    constraints: Optional[Dict[str, Any]] = None
    metadata: Optional[Dict[str, Any]] = None

class AgentCapabilities(BaseModel):
    """Contract defining what an agent can and cannot do."""
    accepts_intents: List[str]
    produces: List[str]
    requires: List[str]

class AgentResponse(BaseModel):
    """Standardized result from an agent execution."""
    status: Literal["success", "failure", "needs_rework"]
    output: Dict[str, Any]
    confidence: Optional[float] = None
    notes: Optional[str] = None

# --- Planning Infrastructure ---

class ExecutionStep(BaseModel):
    """A single step in the multi-agent orchestration."""
    step_id: str
    agent: Literal["researcher", "writer", "coder"]
    intent: str
    instruction: str
    depends_on: List[str] = Field(description="IDs of steps that must finish before this (use empty list if none)")
    requires_review: bool = Field(description="Whether this step requires critic review vs. fast path")

class ExecutionPlan(BaseModel):
    """The master strategy generated by the Planner."""
    steps: List[ExecutionStep]
    strategy_rationale: str

# --- State Management ---

from typing import TypedDict

class AgentState(TypedDict):
    plan: ExecutionPlan
    step_results: Dict[str, AgentResponse]
    current_step: int
    correlation_id: UUID
    last_agent_output: Optional[AgentResponse] # Helper for passing data to critic
    retry_count: int # Track retries for the current step
    critic_feedback: Optional[str] # Feedback from critic to improve next attempt
